[package]
name = "nbt"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.28"
cesu8 = "1.1.0"
byteorder = "1.5.0"
tokio = { version = "1.36.0", features = ["full"] }
async-recursion = "1.0.5"
